# Generated by Django 5.2.5 on 2025-09-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_question_options_remove_question_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pass_score',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
