# Generated by Django 5.2.5 on 2025-09-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_quiz_pass_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='learning.chapter'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_score',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.DeleteModel(
            name='ChapterQuiz',
        ),
    ]
